image: node:20

stages:
  - install
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist   # bei Vite
      # - build  # bei Create React App

coolify_deploy:
  stage: deploy
  image: curlimages/curl:latest
  variables:
    AUTH_HEADER: "Authorization: Bearer $COOLIFY_PRODUCTION_TOK"
  script:
    - curl -X POST "$COOLIFY_PRODUCTION_URL" -H "$AUTH_HEADER"
  only:
    - production